#pragma once

#ifndef __DEFINE_H__
#define __DEFINE_H__

#define WINCX 672
#define WINCY 960
#define PUBLIC_BMP_WIDTH				224
#define PUBLIC_BMP_HEIGHT				320

#define SAFE_DELETE(p) if(p) { delete p; p = nullptr; }

#define OBJ_NOEVENT 0
#define OBJ_DEAD 1

#define PI 3.1415f

#define BACKGROUND_SPEED				0.3334f

#define BACKGROUND_TOTAL_HEIGHT			3266
#define BACKGROUND_WIDTH				224
#define BACKGROUND_HEIGHT				320

// 플레이어
#define ALUCARD_MOVE_WIDTH				32
#define ALUCARD_MOVE_HEIGHT				31

#define MARION_MOVE_WIDTH				23
#define MARION_MOVE_HEIGHT				29
#define MARION_CHARGE_WIDTH				40
#define MARION_CHARGE_HEIGHT			53
#define MARION_BOMB_WIDTH				152
#define MARION_BOMB_HEIGHT				135
#define MARION_MELEE_WIDTH				43
#define MARION_MELEE_HEIGHT				95

#define VALPIRO_MOVE_WIDTH				29
#define VALPIRO_MOVE_HEIGHT				30

#define TAVIA_MOVE_WIDTH				11
#define TAVIA_MOVE_HEIGHT				26

#define HEICOB_MOVE_WIDTH				24
#define HEICOB_MOVE_HEIGHT				32

// 플레이어 총알
#define MARION_BULLET_POWER_1_WIDTH		7
#define MARION_BULLET_POWER_1_HEIGHT	29
#define MARION_BULLET_POWER_2_WIDTH		15
#define MARION_BULLET_POWER_2_HEIGHT	29
#define MARION_BULLET_POWER_3_WIDTH		7
#define MARION_BULLET_POWER_3_HEIGHT	29
#define MARION_BULLET_POWER_4_WIDTH		17
#define MARION_BULLET_POWER_4_HEIGHT	30
#define MARION_GUIDED_BULLET_WIDTH		15
#define MARION_GUIDED_BULLET_HEIGHT		15
#define MARION_CHARGE_BULLET_WIDTH		36
#define MARION_CHARGE_BULLET_HEIGHT		78
#define MARION_CHARGE_BULLET_HIT_WIDTH		62
#define MARION_CHARGE_BULLET_HIT_HEIGHT		62

// 몬스터
#define ROCKET_WIDTH					21
#define ROCKET_HEIGHT					32
#define BLUE_WIDTH						42
#define BLUE_HEIGHT						31
#define MOVER_CANNON_WIDTH				33
#define MOVER_CANNON_HEIGHT				50
#define CANNON_WIDTH					35
#define CANNON_HEIGHT					51
#define CACTUS_WIDTH					28
#define CACTUS_HEIGHT					50
#define ROBOT_BLUE_WIDTH				106
#define ROBOT_BLUE_HEIGHT				102
#define RED_BEANIE_WIDTH				59
#define RED_BEANIE_HEIGHT				49
#define FACTORY_WIDTH					101
#define FACTORY_HEIGHT					101

#define ROBOT_SHARK_WIDTH				74
#define ROBOT_SHARK_HEIGHT				80

// 몬스터 총알
#define BULLET_1_WIDTH					12
#define BULLET_1_HEIGHT					12
#define BULLET_2_WIDTH					16
#define BULLET_2_HEIGHT					16
#define BULLET_3_WIDTH					13
#define BULLET_3_HEIGHT					13
#define BULLET_4_WIDTH					12
#define BULLET_4_HEIGHT					12

// 이펙트
#define BULLET_HIT_WIDTH				14
#define BULLET_HIT_HEIGHT				47
#define EXPLOSION_01_WIDTH				48
#define EXPLOSION_01_HEIGHT				48
#define EXPLOSION_02_1_WIDTH			60
#define EXPLOSION_02_1_HEIGHT			75
#define EXPLOSION_03_WIDTH				112
#define EXPLOSION_03_HEIGHT				109
#define EXPLOSION_04_WIDTH				128
#define EXPLOSION_04_HEIGHT				128
#define EXPLOSION_05_WIDTH				46
#define EXPLOSION_05_HEIGHT				44
#define PLAYER_DEAD_WIDTH				124
#define PLAYER_DEAD_HEIGHT				124
#define BULLET_1_DESTROY_WIDTH			7
#define BULLET_1_DESTROY_HEIGHT			7
#define BULLET_2_DESTROY_WIDTH			10
#define BULLET_2_DESTROY_HEIGHT			10
#define BULLET_3_DESTROY_WIDTH			16
#define BULLET_3_DESTROY_HEIGHT			16
#define BULLET_4_DESTROY_WIDTH			14
#define BULLET_4_DESTROY_HEIGHT			14
#define WHEEL_SMOKE_WIDTH				28
#define WHEEL_SMOKE_HEIGHT				30
#define PIPE_SMOKE_WIDTH				90
#define PIPE_SMOKE_HEIGHT				39
#define MARION_EFFECT_WIDTH				10
#define MARION_EFFECT_HEIGHT			12
#define EFFECT_CHARGE_WIDTH				66
#define EFFECT_CHARGE_HEIGHT			68
#define EFFECT_MARIONMELEEHIT_WIDTH		101
#define EFFECT_MARIONMELEEHIT_HEIGHT	99

// 아이템
#define POWER_UP_WIDTH					20
#define POWER_UP_HEIGHT					13
#define CANDY_WIDTH						28
#define CANDY_HEIGHT					28
#define BOMB_WIDTH						23
#define BOMB_HEIGHT						12
#define COIN_WIDTH						16
#define COIN_HEIGHT						22

// 맵 오브젝트
#define STAGE_1_SIGN_WIDTH				28
#define STAGE_1_SIGN_HEIGHT				48
#define STAGE_1_ROOF_WIDTH				151
#define STAGE_1_ROOF_HEIGHT				85
#define STAGE_1_SHOP_WIDTH				124
#define STAGE_1_SHOP_HEIGHT				160
#define STAGE_1_SHOP_ROOF_WIDTH			190
#define STAGE_1_SHOP_ROOF_HEIGHT		128
#define STAGE_1_BROKEN_SIGN_WIDTH		143
#define STAGE_1_BROKEN_SIGN_HEIGHT		210
#define STAGE_1_RIGHT_ROCK_WIDTH		123
#define STAGE_1_RIGHT_ROCK_HEIGHT		318
#define STAGE_1_LEFT_ROCK_WIDTH			128
#define STAGE_1_LEFT_ROCK_HEIGHT		316
#define STAGE_1_BRIDGE_WIDTH			224
#define STAGE_1_BRIDGE_HEIGHT			233

// NPC
#define SHARK_WIDTH						15
#define SHARK_HEIGHT					26
#define SHARK_DESTROY_WIDTH				13
#define SHARK_DESTROY_HEIGHT			16
#define GIMMICK_WIDTH					23
#define GIMMICK_HEIGHT					36
#define GIMMICK_DESTROY_WIDTH			17
#define GIMMICK_DESTROY_HEIGHT			15
#define BLADE_WIDTH						36
#define BLADE_HEIGHT					32
#define BLADE_DESTROY_WIDTH				19
#define BLADE_DESTROY_HEIGHT			18

// 보스
#define TEQUILA_GROUND_WIDTH			216
#define TEQUILA_GROUND_HEIGHT			217
#define TEQUILA_GALLOP_WIDTH			186
#define TEQUILA_GALLOP_HEIGHT			172


// UI
#define POWER_TEXT_WIDTH				30
#define POWER_TEXT_HEIGHT				12
#define TEXT_BOX_WIDTH					215
#define TEXT_BOX_HEIGHT					55
#define SHARK_STANDING_WIDTH			231
#define SHARK_STANDING_HEIGHT			319
#define GIMMICK_STANDING_WIDTH			183
#define GIMMICK_STANDING_HEIGHT			291
#define BLADE_STANDING_WIDTH			313
#define BLADE_STANDING_HEIGHT			217
#define PLAYER_LIFE_WIDTH				15
#define PLAYER_LIFE_HEIGHT				15
#define UI_BIG_NUMBER_WIDTH				14
#define UI_BIG_NUMBER_HEIGHT			15
#define UI_SMALL_NUMBER_WIDTH			9
#define UI_SMALL_NUMBER_HEIGHT			13
#define MAIN_CONTINUE_WIDTH				224
#define MAIN_CONTINUE_HEIGHT			320
#define UI_PLAYER_NUM_WIDTH				15
#define UI_PLAYER_NUM_HEIGHT			9
#define UI_STAGE_NUM_WIDTH				12
#define UI_STAGE_NUM_HEIGHT				9
#define UI_CHARGE_BAR_WIDTH				70
#define UI_CHARGE_BAR_HEIGHT			19
#define UI_BOMB_WIDTH					16
#define UI_BOMB_HEIGHT					16
#define UI_SCORE_TEXT_WIDTH				11
#define UI_SCORE_TEXT_HEIGHT			7
#define UI_CREDIT_TEXT_WIDTH			39
#define UI_CREDIT_TEXT_HEIGHT			7
#define UI_INSERT_COINS_WIDTH			78
#define UI_INSERT_COINS_HEIGHT			10
#define UI_START_WIDTH					67
#define UI_START_HEIGHT					15

// CG
#define CG_KUSURI_WIDTH					96
#define CG_KUSURI_HEIGHT				135
#define CG_TEXT_BOX_WIDTH				672
#define CG_TEXT_BOX_HEIGHT				192
#define CG_MARION_STANDING_WIDTH		243
#define CG_MARION_STANDING_HEIGHT		320
#define CG_USAGI_STANDING_WIDTH			153
#define CG_USAGI_STANDING_HEIGHT		320


#endif // !__DEFINE_H__
