#pragma once

#ifndef __ENUM_H__
#define __ENUM_H__

namespace OBJID
{
	enum ID { BACKGROUND, BACK_EFFECT, GROUND_MONSTER, GROUND_BOSS, NPC, MAP_OBJECT, UPPER_MONSTER, AIR_MONSTER,
		ITEM, EFFECT, FRONT_EFFECT, PLAYER_BULLET, PLAYER, MONSTER_BULLET,
		SECTOR, REMOVE_SECTOR, UI, END };
}

namespace PLAYER
{
	enum NAME { ALUCARD, MARION, VALPIRO, TAVIA, HEI_COB, AINE, NAME_END };
	enum STATE { IDLE, LEFT_1, LEFT_2, RIGHT_1, RIGHT_2, CHARGE_START, CHARGE_REPEAT, CHARGE_END, BOMB, MELEE, DEAD, RESPAWN, CONTINUE, STATE_END };
}

namespace ITEM
{
	enum TYPE { POWER_UP, BOMB, SCORE, END };
}

namespace OBJTYPE
{
	// 오브젝트 타입
	enum TYPE {
		NO_OBJECT,
		PLAYER,
		ROCKET,
		BLUE,
		RED,
		CANNON,
		CACTUS_CANNON,
		MOVER_CANNON,
		ROBOT_BLUE,
		RED_BEANIE,
		FACTORY,
		ROBOT_SHARK,
		STAGE_1_SIGN,
		STAGE_1_ROOF,
		STAGE_1_SHOP,
		STAGE_1_SHOP_ROOF,
		STAGE_1_BROKEN_SIGN,
		STAGE_1_RIGHT_ROCK,
		STAGE_1_LEFT_ROCK,
		STAGE_1_BRIDGE,
		SHARK,
		GIMMICK,
		BLADE,
		SECTOR,
		TEQUILA_GROUND,
		END
	};
}

enum class BULLETTYPE { BULLET_1, BULLET_2, BULLET_3, BULLET_4, END };


#endif // !__ENUM_H__
